services:

  sisar-execute:
    image: sisar-execute:latest
    container_name: sisar_execute_processor
    env_file:
      - .env
    volumes:
      - ${DATA_DIR:-./data}/slc:/workspace/slc
      - ${DATA_DIR:-./data}/dem:/workspace/dem
      - ${DATA_DIR:-./data}/orbits:/workspace/orbits
      - ${DATA_DIR:-./data}/isce2_output:/workspace/isce2_output
      - ${DATA_DIR:-./data}/series_ps:/workspace/series_ps
      - ${DATA_DIR:-./data}/output:/workspace/output
      - ./config.json:/workspace/config.json
    command: bash /workspace/entrypoint.sh

  mintpy:
    image: mintpy:latest
    container_name: sisar_mintpy_processor
    volumes:
      - ${DATA_DIR:-./data}/isce2_output:/workspace/isce2_output
      - ${DATA_DIR:-./data}/series_ps:/workspace/series_ps
      - ${DATA_DIR:-./data}/output:/workspace/output
    depends_on:
      - sisar-execute
    command: bash /workspace/entrypoint_mintpy.sh
